### PR TITLE
Adding environment variable for server path

### PR DESCRIPTION
**Pull request by drmikecrowe**
…g.json path

### CODE REVIEW

**Comment by doublemarked** [comment]
Hey, thank you for the PR! Can you help me understand the circumstances under which this is necessary? How are is your project set up such that the app can't be found?

**Comment by drmikecrowe** [comment]
I build my docker containers with the node_modules in /dist, and a symlink of /dist/node_modules to the current directory.

For development, we run this docker container and map the current directory into /home/strong-pm, with a symlink of node_modules -> /dist/node_modules
For production, we add the current directory to that base image and cut a docker image with the release code.

For whatever reason, the fact that node_modules isn't in the current directory causes divineLoopbackServerPath to fail.  I thought about debugging this condition, but though that having a way to override/fix it would be needed even if this situation were resolved.

**Comment by doublemarked** [comment]
I see. This module depends on https://github.com/inxilpro/node-app-root-path to determine project root. `app-root-path` already has a means to override its decisions using an env-var, `APP_ROOT_PATH`. Can you try setting `APP_ROOT_PATH` to your project root (wherever package.json exists) and see if it solves your problem?

**Comment by drmikecrowe** [comment]
You are right -- APP_ROOT_PATH solves the same problem.

Can you update the README to include this?  APP_ROOT_PATH=/home/strong-pm solved my problem

**Comment by doublemarked** [comment]
Added to README! Thanks for your feedback.

**Pull request closed without merging**
